name: CI workflow

on:
  pull_request:
    types: [opened, synchoronize, closed]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Unit test
        run: make test

